GET http://ocw48ccw4ko4ock8o4848oo0.35.175.246.204.sslip.io/health

###
POST http://localhost:3000/api/convert
Content-Type: application/json

{
    "url": "https://uklfdugabopbuqmpoiao.supabase.co/storage/v1/object/public/whatsapp-media//recording.webm",
    "outputFormat": "mp3",
    "bitrate": "128k"
}

###
GET http://localhost:3000/api/download/cf5d9f74-2bc7-47de-969f-0571027fb8fa